name: PR Builder
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Prepare lib artifacts
      run: |
        mkdir -p build/lib
        cp ./populate/build/libs/populate.jar build/lib
        cp ./schema/build/libs/schema.jar build/lib

    - name: Upload library artifacts
      uses: actions/upload-artifact@v4
      with:
        name: eu.efti.datatools.lib.${{ github.sha }}
        path: ./build/lib/*

    - name: Upload app artifact
      uses: actions/upload-artifact@v4
      with:
        name: eu.efti.datatools.app.${{ github.sha }}
        path: |
          ./app/build/distributions/app.zip
